name: Lint
on:
  # run on each pull request
  pull_request:
    types: [ synchronize, opened, reopened ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.1.1
      with:
        target: Dockerfile

