name: Lint
on:
  # run on each pull request
  pull_request:
    types: [ synchronize, opened, reopened ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: "bcc-centos7/Dockerfile:ci-env/Dockerfile"

