name: Lint
on:
  # run on each pull request
  pull_request:
    types: [ synchronize, opened, reopened ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: 'bcc-centos7/Dockerfile:ci-env/Dockerfile:clang-format-3.9/Dockerfile:pegasus-build-env/centos7/Dockerfile:pegasus-build-env/ubuntu1604/Dockerfile:pegasus-build-env/ubuntu1804/Dockerfile:pegasus-build-env/ubuntu2004/Dockerfile:pegasus-docker-compose/image_for_prebuilt_bin/Dockerfile:thirdparties-bin/Dockerfile:thirdparties-src/Dockerfile'

